import { AnomalyScore } from "./AnomalyScore";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Copy, Download, Volume2, VolumeX, Share2, FileText, MapPin, AlertCircle } from "lucide-react";
import { toast } from "sonner";
import { useState } from "react";
import { cn } from "@/lib/utils";

interface AnalysisResultProps {
  analysis: {
    anomaly_score: number;
    anomaly_types: string[];
    analysis: string;
    mystery_level?: string;
    coordinates_estimate?: string;
  };
  narration: string;
  imageUrl?: string;
}

export function AnalysisResult({ analysis, narration, imageUrl }: AnalysisResultProps) {
  const [isSpeaking, setIsSpeaking] = useState(false);

  const copyNarration = async () => {
    await navigator.clipboard.writeText(narration);
    toast.success("Copied to clipboard!", {
      description: "Narration ready to paste",
    });
  };

  const speakNarration = () => {
    if (!('speechSynthesis' in window)) {
      toast.error("Speech not supported", {
        description: "Your browser doesn't support text-to-speech",
      });
      return;
    }

    if (isSpeaking) {
      speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    // Cancel any existing speech first
    speechSynthesis.cancel();

    // Create utterance immediately in user gesture context
    const utterance = new SpeechSynthesisUtterance(narration);
    utterance.rate = 0.85;
    utterance.pitch = 0.7;
    utterance.volume = 1.0;
    
    utterance.onstart = () => {
      console.log('Speech started');
      setIsSpeaking(true);
    };
    utterance.onend = () => {
      console.log('Speech ended');
      setIsSpeaking(false);
    };
    utterance.onerror = (e) => {
      console.error('Speech error:', e);
      setIsSpeaking(false);
      toast.error("Speech failed to play");
    };

    // Get voices and set one if available
    const voices = speechSynthesis.getVoices();
    if (voices.length > 0) {
      const englishVoice = voices.find(v => v.lang.startsWith('en')) || voices[0];
      utterance.voice = englishVoice;
    }
    
    // Speak immediately - must happen synchronously in click handler
    setIsSpeaking(true);
    speechSynthesis.speak(utterance);
    
    // Chrome bug workaround: speech can pause after ~15 seconds
    const resumeInterval = setInterval(() => {
      if (!speechSynthesis.speaking) {
        clearInterval(resumeInterval);
      } else {
        speechSynthesis.pause();
        speechSynthesis.resume();
      }
    }, 10000);
    
    utterance.onend = () => {
      clearInterval(resumeInterval);
      setIsSpeaking(false);
    };
  };

  const downloadReport = () => {
    const content = `
╔═══════════════════════════════════════════════════════════════╗
║           EARTH ANOMALY DETECTOR - ANALYSIS REPORT            ║
╚═══════════════════════════════════════════════════════════════╝

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

ANOMALY SCORE: ${analysis.anomaly_score}/10
MYSTERY LEVEL: ${analysis.mystery_level || 'Unknown'}
${analysis.coordinates_estimate ? `COORDINATES: ${analysis.coordinates_estimate}` : ''}

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

DETECTED ANOMALIES:
${analysis.anomaly_types?.map(t => `  ▸ ${t}`).join('\n') || '  ▸ None detected'}

───────────────────────────────────────────────────────────────

AI ANALYSIS:
${analysis.analysis}

───────────────────────────────────────────────────────────────

REEL NARRATION:
"${narration}"

═══════════════════════════════════════════════════════════════
Generated by Earth Anomaly Detector
https://earth-anomaly.lovable.app
═══════════════════════════════════════════════════════════════
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `anomaly-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!", {
      description: "Check your downloads folder",
    });
  };

  const shareResult = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Earth Anomaly Detection',
          text: `Anomaly Score: ${analysis.anomaly_score}/10\n\n${narration}`,
          url: window.location.href,
        });
      } catch (err) {
        // User cancelled
      }
    } else {
      await navigator.clipboard.writeText(`Anomaly Score: ${analysis.anomaly_score}/10\n\n${narration}`);
      toast.success("Copied for sharing!");
    }
  };

  const getMysteryBadgeClass = (level?: string) => {
    switch (level?.toLowerCase()) {
      case 'extreme':
        return 'bg-destructive/20 text-destructive border-destructive/40 animate-pulse';
      case 'high':
        return 'bg-warning/20 text-warning border-warning/40';
      case 'medium':
        return 'bg-primary/20 text-primary border-primary/40';
      default:
        return 'bg-muted/50 text-muted-foreground border-muted-foreground/30';
    }
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header with score */}
      <div className="flex flex-col lg:flex-row items-center gap-8 lg:gap-12">
        {/* Score display */}
        <div className="flex-shrink-0">
          <AnomalyScore score={analysis.anomaly_score} size="lg" animate />
        </div>

        {/* Quick stats */}
        <div className="flex-1 space-y-4 text-center lg:text-left">
          <div className="space-y-2">
            <h3 className="font-display text-2xl text-foreground tracking-wide">
              ANALYSIS COMPLETE
            </h3>
            <div className="flex flex-wrap items-center justify-center lg:justify-start gap-2">
              {analysis.mystery_level && (
                <Badge className={cn("font-display tracking-wider", getMysteryBadgeClass(analysis.mystery_level))}>
                  <AlertCircle className="w-3 h-3 mr-1" />
                  {analysis.mystery_level.toUpperCase()} MYSTERY
                </Badge>
              )}
              {analysis.coordinates_estimate && analysis.coordinates_estimate !== 'Unknown' && (
                <Badge variant="outline" className="border-primary/30 text-primary/80 font-mono">
                  <MapPin className="w-3 h-3 mr-1" />
                  {analysis.coordinates_estimate}
                </Badge>
              )}
            </div>
          </div>

          {/* Anomaly type badges */}
          {analysis.anomaly_types && analysis.anomaly_types.length > 0 && (
            <div className="flex flex-wrap gap-2 justify-center lg:justify-start">
              {analysis.anomaly_types.map((type, index) => (
                <Badge
                  key={index}
                  variant="outline"
                  className="border-primary/40 text-primary font-display tracking-wide text-xs"
                >
                  {type}
                </Badge>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Analysis Card */}
      <Card className="glass-panel border-border/30 overflow-hidden">
        <CardHeader className="pb-4 border-b border-border/30">
          <CardTitle className="font-display text-base text-primary flex items-center gap-2">
            <div className="w-2 h-2 bg-primary rounded-full animate-pulse" />
            <span className="tracking-widest">AI ANALYSIS</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4">
          <p className="text-foreground/90 leading-relaxed text-lg">
            {analysis.analysis}
          </p>
        </CardContent>
      </Card>

      {/* Narration Card - More dramatic styling */}
      <Card className="glass-panel-glow border-destructive/20 overflow-hidden relative">
        <div className="absolute inset-0 bg-gradient-to-br from-destructive/5 via-transparent to-warning/5 pointer-events-none" />
        
        <CardHeader className="pb-4 border-b border-destructive/20 relative">
          <CardTitle className="font-display text-base text-destructive flex items-center gap-2">
            <div className="w-2 h-2 bg-destructive rounded-full animate-pulse" />
            <span className="tracking-widest">REEL NARRATION</span>
          </CardTitle>
        </CardHeader>
        
        <CardContent className="pt-6 space-y-6 relative">
          <div className="relative">
            <div className="absolute -left-2 top-0 bottom-0 w-1 bg-gradient-to-b from-destructive/60 via-warning/40 to-destructive/60 rounded-full" />
            <p className="text-foreground text-xl md:text-2xl leading-relaxed italic pl-4 font-light">
              "{narration}"
            </p>
          </div>
          
          <div className="flex flex-wrap gap-2 pt-2">
            <Button
              variant="outline"
              size="sm"
              onClick={copyNarration}
              className="border-primary/40 hover:border-primary hover:bg-primary/10 font-display tracking-wider text-xs"
            >
              <Copy className="w-3.5 h-3.5 mr-2" />
              COPY
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={speakNarration}
              className={cn(
                "border-primary/40 hover:border-primary hover:bg-primary/10 font-display tracking-wider text-xs",
                isSpeaking && "border-primary bg-primary/20"
              )}
            >
              {isSpeaking ? (
                <>
                  <VolumeX className="w-3.5 h-3.5 mr-2" />
                  STOP
                </>
              ) : (
                <>
                  <Volume2 className="w-3.5 h-3.5 mr-2" />
                  SPEAK
                </>
              )}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={downloadReport}
              className="border-primary/40 hover:border-primary hover:bg-primary/10 font-display tracking-wider text-xs"
            >
              <FileText className="w-3.5 h-3.5 mr-2" />
              REPORT
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={shareResult}
              className="border-primary/40 hover:border-primary hover:bg-primary/10 font-display tracking-wider text-xs"
            >
              <Share2 className="w-3.5 h-3.5 mr-2" />
              SHARE
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
