import { AnomalyScore } from "./AnomalyScore";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Copy, Download, Share2, Volume2 } from "lucide-react";
import { toast } from "sonner";

interface AnalysisResultProps {
  analysis: {
    anomaly_score: number;
    anomaly_types: string[];
    analysis: string;
    mystery_level?: string;
  };
  narration: string;
  imageUrl?: string;
}

export function AnalysisResult({ analysis, narration, imageUrl }: AnalysisResultProps) {
  const copyNarration = () => {
    navigator.clipboard.writeText(narration);
    toast.success("Narration copied to clipboard!");
  };

  const speakNarration = () => {
    if ('speechSynthesis' in window) {
      const utterance = new SpeechSynthesisUtterance(narration);
      utterance.rate = 0.8;
      utterance.pitch = 0.8;
      speechSynthesis.speak(utterance);
      toast.success("Speaking narration...");
    } else {
      toast.error("Speech synthesis not supported in this browser");
    }
  };

  const downloadContent = () => {
    const content = `
EARTH ANOMALY ANALYSIS REPORT
=============================

ANOMALY SCORE: ${analysis.anomaly_score}/10
MYSTERY LEVEL: ${analysis.mystery_level || 'Unknown'}

DETECTED ANOMALIES:
${analysis.anomaly_types?.map(t => `• ${t}`).join('\n') || 'None detected'}

ANALYSIS:
${analysis.analysis}

REEL NARRATION:
"${narration}"

Generated by Earth Anomaly Detector
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `anomaly-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!");
  };

  return (
    <div className="space-y-6">
      {/* Main Score Display */}
      <div className="flex flex-col items-center py-8">
        <AnomalyScore score={analysis.anomaly_score} size="lg" />
      </div>

      {/* Anomaly Types */}
      {analysis.anomaly_types && analysis.anomaly_types.length > 0 && (
        <div className="flex flex-wrap gap-2 justify-center">
          {analysis.anomaly_types.map((type, index) => (
            <Badge
              key={index}
              variant="outline"
              className="border-primary/50 text-primary font-display tracking-wide"
            >
              {type}
            </Badge>
          ))}
        </div>
      )}

      {/* Analysis Card */}
      <Card className="glass-panel border-border/50">
        <CardHeader className="pb-3">
          <CardTitle className="font-display text-lg text-primary flex items-center gap-2">
            <span className="w-2 h-2 bg-primary rounded-full animate-pulse" />
            AI ANALYSIS
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-foreground/90 leading-relaxed">
            {analysis.analysis}
          </p>
        </CardContent>
      </Card>

      {/* Narration Card */}
      <Card className="glass-panel border-destructive/30 bg-gradient-to-br from-destructive/5 to-warning/5">
        <CardHeader className="pb-3">
          <CardTitle className="font-display text-lg text-destructive flex items-center gap-2">
            <span className="w-2 h-2 bg-destructive rounded-full animate-pulse" />
            REEL NARRATION
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-foreground italic text-lg leading-relaxed">
            "{narration}"
          </p>
          
          <div className="flex flex-wrap gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={copyNarration}
              className="border-primary/50 hover:bg-primary hover:text-primary-foreground"
            >
              <Copy className="w-4 h-4 mr-2" />
              Copy
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={speakNarration}
              className="border-primary/50 hover:bg-primary hover:text-primary-foreground"
            >
              <Volume2 className="w-4 h-4 mr-2" />
              Speak
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={downloadContent}
              className="border-primary/50 hover:bg-primary hover:text-primary-foreground"
            >
              <Download className="w-4 h-4 mr-2" />
              Download
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}