import { AnomalyScore } from "./AnomalyScore";
import { AudioVisualizer } from "./effects/AudioVisualizer";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { 
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Copy, Download, Volume2, VolumeX, Share2, FileText, MapPin, AlertCircle, Loader2, Mic } from "lucide-react";
import { toast } from "sonner";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { usePremiumTTS, PREMIUM_VOICES } from "@/hooks/use-premium-tts";

interface AnalysisResultProps {
  analysis: {
    anomaly_score: number;
    anomaly_types: string[];
    analysis: string;
    mystery_level?: string;
    coordinates_estimate?: string;
  };
  narration: string;
  imageUrl?: string;
}

export function AnalysisResult({ analysis, narration, imageUrl }: AnalysisResultProps) {
  const [selectedVoice, setSelectedVoice] = useState<string>(PREMIUM_VOICES[0].id);
  
  const { speak, stop, isLoading, isPlaying, audioElement } = usePremiumTTS({
    voiceId: selectedVoice,
  });

  const copyNarration = async () => {
    await navigator.clipboard.writeText(narration);
    toast.success("Copied to clipboard!", {
      description: "Narration ready to paste",
    });
  };

  const handleSpeak = async () => {
    if (isPlaying || isLoading) {
      stop();
      return;
    }
    await speak(narration);
  };

  const downloadReport = () => {
    const content = `
╔═══════════════════════════════════════════════════════════════╗
║           EARTH ANOMALY DETECTOR - ANALYSIS REPORT            ║
╚═══════════════════════════════════════════════════════════════╝

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

ANOMALY SCORE: ${analysis.anomaly_score}/10
MYSTERY LEVEL: ${analysis.mystery_level || 'Unknown'}
${analysis.coordinates_estimate ? `COORDINATES: ${analysis.coordinates_estimate}` : ''}

▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

DETECTED ANOMALIES:
${analysis.anomaly_types?.map(t => `  ▸ ${t}`).join('\n') || '  ▸ None detected'}

───────────────────────────────────────────────────────────────

AI ANALYSIS:
${analysis.analysis}

───────────────────────────────────────────────────────────────

REEL NARRATION:
"${narration}"

═══════════════════════════════════════════════════════════════
Generated by Earth Anomaly Detector
https://earth-anomaly.lovable.app
═══════════════════════════════════════════════════════════════
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `anomaly-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded!", {
      description: "Check your downloads folder",
    });
  };

  const shareResult = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Earth Anomaly Detection',
          text: `Anomaly Score: ${analysis.anomaly_score}/10\n\n${narration}`,
          url: window.location.href,
        });
      } catch (err) {
        // User cancelled
      }
    } else {
      await navigator.clipboard.writeText(`Anomaly Score: ${analysis.anomaly_score}/10\n\n${narration}`);
      toast.success("Copied for sharing!");
    }
  };

  const getMysteryBadgeClass = (level?: string) => {
    switch (level?.toLowerCase()) {
      case 'extreme':
        return 'bg-destructive/20 text-destructive border-destructive/40 animate-pulse';
      case 'high':
        return 'bg-warning/20 text-warning border-warning/40';
      case 'medium':
        return 'bg-primary/20 text-primary border-primary/40';
      default:
        return 'bg-muted/50 text-muted-foreground border-muted-foreground/30';
    }
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header with score */}
      <div className="flex flex-col lg:flex-row items-center gap-8 lg:gap-12">
        {/* Score display */}
        <div className="flex-shrink-0">
          <AnomalyScore score={analysis.anomaly_score} size="lg" animate />
        </div>

        {/* Quick stats */}
        <div className="flex-1 space-y-4 text-center lg:text-left">
          <div className="space-y-2">
            <h3 className="font-display text-2xl text-foreground tracking-wide">
              ANALYSIS COMPLETE
            </h3>
            <div className="flex flex-wrap items-center justify-center lg:justify-start gap-2">
              {analysis.mystery_level && (
                <Badge className={cn("font-display tracking-wider", getMysteryBadgeClass(analysis.mystery_level))}>
                  <AlertCircle className="w-3 h-3 mr-1" />
                  {analysis.mystery_level.toUpperCase()} MYSTERY
                </Badge>
              )}
              {analysis.coordinates_estimate && analysis.coordinates_estimate !== 'Unknown' && (
                <Badge variant="outline" className="border-primary/30 text-primary/80 font-mono">
                  <MapPin className="w-3 h-3 mr-1" />
                  {analysis.coordinates_estimate}
                </Badge>
              )}
            </div>
          </div>

          {/* Anomaly type badges */}
          {analysis.anomaly_types && analysis.anomaly_types.length > 0 && (
            <div className="flex flex-wrap gap-2 justify-center lg:justify-start">
              {analysis.anomaly_types.map((type, index) => (
                <Badge
                  key={index}
                  variant="outline"
                  className="border-primary/40 text-primary font-display tracking-wide text-xs"
                >
                  {type}
                </Badge>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Analysis Card */}
      <Card className="glass-panel border-border/30 overflow-hidden">
        <CardHeader className="pb-4 border-b border-border/30">
          <CardTitle className="font-display text-base text-primary flex items-center gap-2">
            <div className="w-2 h-2 bg-primary rounded-full animate-pulse" />
            <span className="tracking-widest">AI ANALYSIS</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-4">
          <p className="text-foreground/90 leading-relaxed text-lg">
            {analysis.analysis}
          </p>
        </CardContent>
      </Card>

      {/* Narration Card - More dramatic styling */}
      <Card className="glass-panel-glow border-destructive/20 overflow-hidden relative">
        <div className="absolute inset-0 bg-gradient-to-br from-destructive/5 via-transparent to-warning/5 pointer-events-none" />
        
        <CardHeader className="pb-4 border-b border-destructive/20 relative">
          <CardTitle className="font-display text-base text-destructive flex items-center gap-2">
            <div className="w-2 h-2 bg-destructive rounded-full animate-pulse" />
            <span className="tracking-widest">REEL NARRATION</span>
          </CardTitle>
        </CardHeader>
        
        <CardContent className="pt-6 space-y-6 relative">
          <div className="relative">
            <div className="absolute -left-2 top-0 bottom-0 w-1 bg-gradient-to-b from-destructive/60 via-warning/40 to-destructive/60 rounded-full" />
            <p className="text-foreground text-xl md:text-2xl leading-relaxed italic pl-4 font-light">
              "{narration}"
            </p>
          </div>

          {/* Audio Visualizer */}
          {(isPlaying || isLoading) && (
            <div className="glass-panel p-4 rounded-lg">
              <AudioVisualizer 
                isPlaying={isPlaying} 
                audioElement={audioElement}
                barCount={32}
                variant="bars"
              />
            </div>
          )}

          {/* Voice Selection & Controls */}
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <Mic className="w-3.5 h-3.5" />
              <span className="font-mono uppercase tracking-wider">Voice:</span>
            </div>
            <Select value={selectedVoice} onValueChange={setSelectedVoice} disabled={isPlaying || isLoading}>
              <SelectTrigger className="w-[180px] h-8 text-xs">
                <SelectValue placeholder="Select voice" />
              </SelectTrigger>
              <SelectContent>
                {PREMIUM_VOICES.map(voice => (
                  <SelectItem key={voice.id} value={voice.id} className="text-xs">
                    <span className="font-medium">{voice.name}</span>
                    <span className="text-muted-foreground ml-1">- {voice.description}</span>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          
          <div className="flex flex-wrap gap-2 pt-2">
            <Button
              variant="outline"
              size="sm"
              onClick={copyNarration}
              className="border-primary/40 hover:border-primary hover:bg-primary/10 font-display tracking-wider text-xs"
            >
              <Copy className="w-3.5 h-3.5 mr-2" />
              COPY
            </Button>
            <Button
              variant={isPlaying ? "destructive" : "default"}
              size="sm"
              onClick={handleSpeak}
              disabled={isLoading}
              className={cn(
                "font-display tracking-wider text-xs min-w-[100px]",
                !isPlaying && "bg-primary hover:bg-primary/90"
              )}
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 mr-2 animate-spin" />
                  LOADING
                </>
              ) : isPlaying ? (
                <>
                  <VolumeX className="w-3.5 h-3.5 mr-2" />
                  STOP
                </>
              ) : (
                <>
                  <Volume2 className="w-3.5 h-3.5 mr-2" />
                  LISTEN
                </>
              )}
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={downloadReport}
              className="border-primary/40 hover:border-primary hover:bg-primary/10 font-display tracking-wider text-xs"
            >
              <FileText className="w-3.5 h-3.5 mr-2" />
              REPORT
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={shareResult}
              className="border-primary/40 hover:border-primary hover:bg-primary/10 font-display tracking-wider text-xs"
            >
              <Share2 className="w-3.5 h-3.5 mr-2" />
              SHARE
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
